### ISSUE TITLE
SHAP Feature Values Inverted

### ISSUE THREAD

**Issue by chrisrichgruber** [BCG-Gamma/facet#245]
It appears the SHAP summary plot has the 'Feature Value' Inverted.  Your classification example has 'Waist_to_Height' to be positively correlated with 'Prediabetes'.

![image](https://user-images.githubusercontent.com/50928802/108012032-5aae7800-6fd6-11eb-8f0a-d4e677e43f5c.png)

From the SHAP output, you can see a higher values of 'Waist_to_Height' (values in red) have negative impact on model, which is the opposite.

![image](https://user-images.githubusercontent.com/50928802/108011901-1327ec00-6fd6-11eb-9cb0-e8519bb0c76b.png)

I've also tested this using the FACET package and then just running a separate RF model to get the SHAP output outside of FACET and the non-FACET SHAP outputs are as expected and not inverted.

**Comment by chrisrichgruber** [comment]
Adding a "-1" to the code fixes the issue.
`shap.summary_plot(shap_values=-1*shap_data.shap_values, features=shap_data.features, show=False, plot_size=(16.0, 8.0))
`

**Comment by mgelsm** [comment]
Hi chrisrichgruber!
Thanks for raising this issue! we will fix it shortly :)

**Comment by j-ittner** [comment]
@chrisrichgruber thanks for spotting this! This is actually expected behaviour for SHAP explanations of LGBM classifiers, but the sign reversal is confusing so definitely something we'll address in the tutorial.

The reason the model output is reversed is that the SHAP explanations are about raw model output, which is not probability but log-odds; in the case of LGBM the raw values appear to be "negative log-odds" i.e. the exponent `x` in `1 / 1 + exp(x)` (I could not find a clear specification of this in the LGBM documentation) hence the apparent reversal of the effect.

You can easily validate this with a fabricated dataset. It also makes sense for the diabetes dataset from a practical perspective: age and obesity increase diabetes risk.

**Comment by j-ittner** [comment]
Addressing this with PR #274, ensuring the learner inspector returns the SHAP values for the positive class. These will have the expected sign.
