### ISSUE TITLE
Versioning & Compatibility XGBoost

### ISSUE THREAD

**Issue by straussmaximilian** [BCG-Gamma/facet#359]
Hi,
Thanks for making this tool openly available. Very cool. 

While I could get it to run, I do face some issues due to versioning and compatibility that I wanted to report:
(1) When following the conda Installation instructions, one will install `2.0rc2`. This breaks the Quickstart Tutorial:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 11
      9 # relevant FACET imports
     10 from facet.data import Sample
---> 11 from facet.selection import LearnerRanker, LearnerGrid
     13 # declaring url with data
     14 data_url = 'https://web.stanford.edu/~hastie/Papers/LARS/diabetes.data'

ImportError: cannot import name 'LearnerRanker' from 'facet.selection' (C:\Users\admin\.conda\envs\jakob-facet\lib\site-packages\facet\selection\__init__.py)

```

(2) Ideally, I want to run facet with XGBoost. While the core functionality is in sklearndf 2.1.0, facet pins this to version ~= 1.2. 
Unfortunately, the newer sklearndf is not compatible, see the following error running 2.1.0 in facet 1.2.3

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 54
     51 rkf_cv = RepeatedKFold(n_splits=5, n_repeats=10, random_state=42)
     53 # rank your candidate models by performance (default is mean CV score - 2*SD)
---> 54 ranker = LearnerRanker(
     55     grids=rnd_forest_grid, cv=rkf_cv, n_jobs=-3
     56 ).fit(sample=diabetes_sample)
     58 # get summary report
     59 ranker.summary_report()

File ~/miniconda3/envs/facet/lib/python3.8/site-packages/facet/selection/_selection.py:400, in LearnerRanker.fit(self, sample, **fit_params)
    387 """
    388 Rank the candidate learners and their hyper-parameter combinations using
    389 crossfits from the given sample.
   (...)
    396 :return: ``self``
    397 """
    398 self: LearnerRanker[T_LearnerPipelineDF]  # support type hinting in PyCharm
--> 400 ranking: List[LearnerEvaluation[T_LearnerPipelineDF]] = self._rank_learners(
    401     sample=sample, **fit_params
    402 )
    403 ranking.sort(key=lambda le: le.ranking_score, reverse=True)
    405 self._ranking = ranking
...
--> 873     obj = super().__new__(cls)
    874 else:
    875     obj = super().__new__(cls, *args, **kwds)

TypeError: Can't instantiate abstract class _FitScoreQueue with abstract methods aggregate
```
Is there a workaround to get it to run with XGBoost?

(3) On another note: I did experience a quadratic increase in memory consumption with the number of features. For a workstation with 128 GB RAM this effectively limits me to ~100  features (@ ~ 5000 rows).  Is this expected?

**Comment by j-ittner** [comment]
Hi @straussmaximilian , thanks for reaching out! Great questions.

1. We have made some API improvements for the upcoming 2.0 release - you can find the draft documentation [here](https://bcg-gamma.github.io/facet/docs-version/2-0/_generated/getting_started.html), including revised [tutorial notebooks](https://bcg-gamma.github.io/facet/docs-version/2-0/tutorial/Water_Drilling_Incident_Classification_with_Facet.html). While our aim is to stay true to scikit-learn, we have added some helpers like the `ParameterSpace` class that help us prevent bugs in day-to-day model tuning. Let us know what you think.
2. This is true for facet 1.2, but with facet 2.0rc0 you will be able to use scikit-learn 1.2
3. Facet 2.0 is more memory efficient, so that in itself may solve the issue. 128GB sounds plenty for 100 features / 5000 rows - were you able to pinpoint where the memory consumption occurs? For reference, FACET will compute a cube of 100 x 100 x 5000 SHAP interaction values & then do some vector arithmetic based on this. Memory consumption will go further up by the number of parallel threads which will all work on copies of the data. In any case - you may want to try Boruta to eliminate non-relevant features, and you might also want to work with a subsample to reduce the number of rows; in many cases 1000 rows is plenty. 

Hope this provides a few pointers to get you started with facet 2.0! Don't hesitate to reach out with additional questions!
